### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by xiongqi123123** [qrzyang/UHP#1]
Hello, while reproducing your project, I noticed that you used RCF to perform edge detection on the KITTI dataset. However, I would like to ask if the dataset under the 'edge' folder was processed on image2, image3, or disp_occ-0? And what are the parameters of the test output in this code?

**Comment by xiongqi123123** [comment]
What I mean is, which KITTI data generated the data in the edge folder

**Comment by qrzyang** [comment]
Most current self-supervised stereo matching algorithms, including the one presented in this paper, employ a warping strategy where the right image is warped to align with the left image for loss function calculation. Consequently, edge detection is also performed on the left image, specifically image2.

**Comment by xiongqi123123** [comment]
Very Thank！！！
